name: Primer workflow

on: push

jobs:
  validar:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar mensjae
        run: echo "Hola"

      - name: Bajar codigo
        uses: actions/checkout@v5

      - name: Probar codigo
        run: pyhton3 main.py
